EventCountDecreasingError
========================================================

```{r eval=TRUE, echo=FALSE}
knitr::opts_chunk$set(
  fig.width=10,
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  fig.path='figure/',
  cache.path='cache/'
)
```


### Date 

Compiled on `r Sys.time()`

### Setup

> change directory to /data-quality/alerts

```{r child='alertssetup.Rmd'}
```

```{r eval=FALSE}
knitr::purl("alertssetup.Rmd")
source("alertssetup.R")
unlink("alertssetup.R")
```

### Get data

```{r}
(res <- alerts_by_class(class_name='EventCountDecreasingError', limit=10000L))
```

Remove Mendeley data

```{r nomendeley}
res <- res %>% filter(!source == "mendeley")
```

Clean out PLOS Currents urls

```{r alertsclean}
res <- res %>% filter(grepl('journal', article))
res <- res %>% 
  rename(doi = article, alert_class = class, alert_source = source, alert_create_date = create_date, alert_id = id, alert_val = val, alert_from = from, alert_to = to)
```

There can be a lot of data from Crossref, so let's take the top 50 from that source

```{r}
cr_top50 <- res %>%
  filter(alert_source == "crossref") %>%
  arrange(desc(alert_val)) %>%
  data.frame %>%
  .[1:50,]
restop <- tbl_df(rbind(cr_top50, res %>% filter(alert_source != "crossref")))
```

Get ALM events data and merge alerts data to it

```{r}
# altmetrics totals data
idsdata <- alm_ids(restop$doi)
almdat <- function(x, y){
  dat <- x$total
  names(dat) <- x$.id
  data.frame(doi=y, t(data.frame(dat, stringsAsFactors = FALSE)), stringsAsFactors = FALSE)
}
idsdata2 <- rbind_all(Map(almdat, idsdata$data, names(idsdata$data)))

# events data
events <- lapply(restop$doi, alm_events)
names(events) <- restop$doi
# limit events to certain sources of data
sources <- c("counter", unique(res$alert_source))
eventsdata <- lapply(events, function(x) x[names(x) %in% sources])

foo <- function(x, y){
  tmp <- x$counter$events
  z <- if(NROW(tmp) == 0) data.frame(year=NA, month=NA, pdf_views=NA, html_views=NA, xml_views=NA) else tmp
  data.frame(doi=y, z, stringsAsFactors = FALSE)
}
events_counter <- Map(foo, eventsdata, names(eventsdata))
eventsdf <- tbl_df(rbind_all(events_counter))
alldf <- inner_join(x=eventsdf, y=res)
alldf <- inner_join(x=alldf, y=idsdata2)
alldf <- alldf %>% 
    mutate(date = as.Date(sprintf('%s-%s-01', year, month)))
alldf$alert_create_date <- as.Date(ymd_hms(alldf$alert_create_date))
alldf
```

WOS data

```{r}
alldf %>%
  filter(alert_source == "wos") %>%
  ggplot(aes(date, html_views, color=doi)) +
    geom_line(size = 2, alpha = 0.7)
```

pmceurope data

```{r}
alldf %>%
  filter(alert_source == "pmceurope") %>%
  ggplot(aes(date, html_views, color=doi)) +
    geom_line(size = 2, alpha = 0.7)
```

pmceuropedata data

```{r}
alldf %>%
  filter(alert_source == "pmceuropedata") %>%
  ggplot(aes(date, html_views, color=doi)) +
    geom_line(size = 2, alpha = 0.7)
```

pubmed data

```{r}
alldf %>%
  filter(alert_source == "pubmed") %>%
  ggplot(aes(date, html_views, color=doi)) +
    geom_line(size = 2, alpha = 0.7)
```

citeulike data

```{r}
alldf %>%
  filter(alert_source == "citeulike") %>%
  ggplot(aes(date, html_views, color=doi)) +
    geom_line(size = 2, alpha = 0.7)
```
