#### EventCountDecreasingError

Get data

```{r}
(res <- alerts_by_class(class_name='EventCountDecreasingError', limit=2000))
```

Extract top N articles, get DOIs

```{r}
get <- 1:10
toinspect <- res[get,] %>% select(-class)
(dois <- toinspect$article)
```

Get ALM events data and merge alerts data to it

```{r}
idsdata <- alm_ids(dois, source = unique(res[get,"source"]))

events <- alm_events(dois, source = unique(res[get,"source"]))
foo <- function(x, y){
  tmp <- x$counter$events
  data.frame(article=y, tmp, stringsAsFactors = FALSE)
}
events <- Map(foo, events, names(events))
eventsdf <- tbl_df(rbind_all(events))
alldf <- inner_join(x=eventsdf, y=toinspect)
alldf <- alldf %>% 
    mutate(date = as.Date(sprintf('%s-%s-01', year, month))) 
alldf$create_date <- as.Date(ymd_hms(alldf$create_date))
```

Plot data, top 10 DOIs

```{r fig.width=10}
alldf %>%
  select(-year, -month, -id, -val, -source) %>%
  gather(metric, value, -article, -date, -create_date) %>%
#   arrange() %>%
  ggplot(aes(date, value, color=metric)) + 
    geom_line(size = 2, alpha = 0.7) + 
    geom_vline(aes(xintercept=as.numeric(create_date)), linetype="longdash") +
    facet_wrap(~ article, ncol = 2, scales = "free") +
    ggtitle("HtmlRatioTooHighError - Top ten highest HTML/PDF ratio articles\n")
```

Dig in to particular DOIs. This is rather free-form, depends on the metric of interest.

```{r eval=FALSE}
doi1 <- '10.1371/journal.pbio.0040066'
alm_events(doi1, source = "facebook")
alm_ids(doi1, info = "detail")
```

Are the high value offender DOIs associated with other alm metrics, like social media metrics

```{r}
dat <- alm_ids(res$article[1:100], source = c("facebook","twitter"))
datdf <- rbind_all(dat$data)
datdf$article <- rep(res$article[1:100], each = 2)
datdf <- inner_join(datdf, res %>% filter(article %in% res$article[1:20]) %>% select(article, val) )

datdf %>% 
  ggplot(aes(x=val, y=total)) + 
    geom_point(aes(size=2)) +
    facet_wrap(~ .id, scales='free') +
    labs(y="", x="") +
    theme_grey(base_size = 18) +
    theme(legend.position="none")
```
