data-quality code
========================================================

Install below packages are not installed already, then load package

```{r}
# install.packages(c('data.table','dplyr','stringr'))
# devtools::install_github("ropensci/alm", ref="alerts")
library('data.table')
library('dplyr')
library('stringr')
library('alm')
```

Read in data

PLOS folks, Monthly reports are in a Google Drive folder, talk to Martin

```{r}
setwd("~/Google Drive/ALM Monthly Reports/") 
files <- list.files(".", pattern = ".csv")
read_file <- function(x){
  tmp <- read.csv(x, header = TRUE, sep = ",", stringsAsFactors=FALSE)
  tmp$datafrom <- str_extract(x, "[0-9]{4}-[0-9]{2}-[0-9]{2}")
  tmp
}
dat <- lapply(files, read_file)
alldat <- rbind_all(dat)
(dat2 <- tbl_df(alldat))
```

Data manipulation

```{r}
# new column with date for each row, drop other pub date columns
# and move title to end for easier viewing
(dat2 <- dat2 %>%
  mutate(pubdate = published[1], title2 = title) %>%
  select(-published, -publication_date, -title))

# remove negative numbers in facebook
(dat2 <- dat2 %>%
  filter(facebook >= 0))

# 
dat2 %>%
  filter(doi == '10.1371/journal.pbio.0030057') %>%
  select(doi, datafrom, twitter)

dat2 %>%
  filter(twitter > 0) %>%

```
